# Generated by Django 2.1.7 on 2019-12-16 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='page',
            new_name='UserInfo',
        ),
    ]
