# Generated by Django 2.1.7 on 2019-12-16 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0002_auto_20191216_1728'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userinfo',
            options={'default_permissions': (), 'permissions': (('admin', 'manager the page'), ('manager', 'manager the project'), ('personal', 'personal'))},
        ),
    ]
