# Generated by Django 2.1.7 on 2019-12-16 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0003_auto_20191216_1733'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserInfo',
        ),
    ]
