# Generated by Django 2.1.7 on 2019-12-31 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('demo', '0004_delete_userinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='checkResult',
            fields=[
                ('tableID', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=256)),
                ('tableName', models.TextField(max_length=32)),
                ('data', models.CharField(max_length=10000)),
            ],
        ),
    ]
