# Generated by Django 2.1.7 on 2019-12-31 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0005_checkresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkresult',
            name='data',
            field=models.CharField(max_length=100000),
        ),
        migrations.AlterField(
            model_name='checkresult',
            name='title',
            field=models.CharField(max_length=10000),
        ),
    ]
