# Generated by Django 2.1.7 on 2019-12-31 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0007_auto_20191231_1529'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkresult',
            old_name='data',
            new_name='TD_data',
        ),
        migrations.RenameField(
            model_name='checkresult',
            old_name='title',
            new_name='TH_title',
        ),
    ]
