# Generated by Django 2.1.7 on 2020-01-02 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0008_auto_20191231_1549'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadFileSingle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='files/%Y/%m/%d')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='checkresult',
            name='TD_data',
        ),
        migrations.AddField(
            model_name='checkresult',
            name='data',
            field=models.CharField(blank=True, max_length=100000),
        ),
    ]
