# Generated by Django 2.1.7 on 2020-01-02 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0009_auto_20200102_1600'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkresult',
            old_name='data',
            new_name='TD_data',
        ),
    ]
