# Generated by Django 2.1.7 on 2020-01-02 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0010_auto_20200102_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfilesingle',
            name='file',
            field=models.FileField(upload_to='demo/static/'),
        ),
    ]
