# Generated by Django 2.1.7 on 2020-01-09 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0014_userinfo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkresult',
            old_name='TH_title',
            new_name='thName',
        ),
    ]
