# Generated by Django 2.1.7 on 2020-01-09 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0015_auto_20200109_1630'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='checkResult',
            new_name='tableData',
        ),
    ]
