# Generated by Django 2.1.7 on 2020-01-09 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0016_auto_20200109_1637'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tabledata',
            name='tableID',
        ),
        migrations.AlterField(
            model_name='tabledata',
            name='tableName',
            field=models.CharField(max_length=32, primary_key=True, serialize=False),
        ),
    ]
