# Generated by Django 2.1.7 on 2020-01-09 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0017_auto_20200109_1653'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tabledata',
            options={'ordering': ['tableName']},
        ),
    ]
