# Generated by Django 3.0.7 on 2020-06-29 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0002_auto_20200629_1201'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserProfile',
            new_name='register',
        ),
    ]
